# GMM data EDA

Here we consider different data sets for the GMM.

## Potential data sets

- [KDD cup 2004](#KDD-cup-2004)
- [Magic 04](#Magic-04)
- [Waveform](#Waveform)
- [Vowels](#Vowels)


Note: many data sets were taken from [Qiong's paper](https://arxiv.org/pdf/2010.10412.pdf),
which has [publicly available code](https://github.com/SarahQiong/SCGMM/tree/main)
(but the real-data experiments are not there I think).

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys

sys.path.insert(1, '../src/')
import madmix
import gibbs
from concrete import *
import aux

plt.rcParams.update({'figure.max_open_warning': 0})
plt.rcParams["figure.figsize"]=15,7.5
plt.rcParams.update({'font.size': 40})
fig_path='fig/'
fig_path='../../../discrete-ergodic-flows-tex/fig/'

## KDD cup 2004

- Link to data: http://localhost:8888/notebooks/ipynb/GMM%20Data.ipynb#KDD-cup-2004
- Description: predicting whether proteins are homologous to the native sequence or decoys
- Dimensions: 145,751 observations in a 74-dimensional space
- Source: page 21 of [Qiong's paper](https://arxiv.org/pdf/2010.10412.pdf); also page 11 of [Lucic et al. (2017)](https://arxiv.org/pdf/1703.08110.pdf)

Pros:
- used in various papers for GMM fitting

Cons:
- hard to fit, high-dimensional (papers it is used in are for coresets)

In [6]:
kdd_dat = pd.read_table('dat/data_kddcup04/bio_train.dat',header=None)

In [7]:
kdd_dat

,0,1,2,3,4,5,6,7,8,9,...,67,68,69,70,71,72,73,74,75,76
0,279,261532,0,52.00,32.69,0.30,2.5,20.0,1256.8,-0.89,...,-8.0,1595.1,-1.64,2.83,-2.0,-50.0,445.2,-0.35,0.26,0.76
1,279,261533,0,58.00,33.33,0.00,16.5,9.5,608.1,0.50,...,-6.0,762.9,0.29,0.82,-3.0,-35.0,140.3,1.16,0.39,0.73
2,279,261534,0,77.00,27.27,-0.91,6.0,58.5,1623.6,-1.40,...,7.0,1491.8,0.32,-1.29,0.0,-34.0,658.2,-0.76,0.26,0.24
3,279,261535,0,41.00,27.91,-0.35,3.0,46.0,1921.6,-1.36,...,6.0,2047.7,-0.98,1.53,0.0,-49.0,554.2,-0.83,0.39,0.73
4,279,261536,0,50.00,28.00,-1.32,-9.0,12.0,464.8,0.88,...,-14.0,479.5,0.68,-0.59,2.0,-36.0,-6.9,2.02,0.14,-0.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145746,48,44821,0,98.61,20.66,2.07,37.0,-70.5,1015.7,0.67,...,-40.0,416.9,1.73,2.49,9.0,-87.0,464.7,0.63,0.45,0.69
145747,48,44822,0,73.15,24.85,0.61,32.5,-40.5,650.2,1.58,...,168.0,1354.3,0.05,-1.14,-4.0,-43.0,304.1,-0.02,0.10,-0.66
145748,48,44823,1,100.00,71.76,41.92,954.5,-1039.0,-562.3,5.19,...,-171.0,-236.2,3.56,11.87,47.0,-175.0,-245.3,3.41,0.44,0.78
145749,48,44824,0,85.65,26.46,1.85,42.0,26.0,2738.3,-0.85,...,-42.0,1919.2,-0.34,-0.98,-16.0,-89.0,12.0,2.88,0.54,0.77
145750,48,44825,1,87.50,29.33,5.84,130.0,-188.5,1297.3,0.44,...,-103.0,716.2,1.82,4.49,18.0,-117.0,607.8,-0.58,0.16,0.23

## Magic 04

- Link to data: https://archive.ics.uci.edu/dataset/159/magic+gamma+telescope
- Description: registration of high energy gamma particles in a ground-based atmospheric Cherenkov gamma telescope using the imaging technique
- Dimensions: 19,020 observations in a 10-dimensional space
- Source: page 21 of [Qiong's paper](https://arxiv.org/pdf/2010.10412.pdf)

Pros:
- Not as high-dimensional. Observations large but can be subsampled

Cons:
- Data were simulated, not real

In [27]:
magic_dat = pd.read_table('dat/magic+gamma+telescope/magic04.data',sep=None,header=None)

/var/folders/k3/24b0dzl557v5m0_0658q2cxr0000gn/T/ipykernel_85796/3606077473.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
  magic_dat = pd.read_table('dat/magic+gamma+telescope/magic04.data',sep=None,header=None)

In [28]:
magic_dat

,0,1,2,3,4,5,6,7,8,9,10
0,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.0110,-8.2027,40.0920,81.8828,g
1,31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.2610,g
2,162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.7880,g
3,23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.7370,g
4,75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.4620,g
...,...,...,...,...,...,...,...,...,...,...,...
19015,21.3846,10.9170,2.6161,0.5857,0.3934,15.2618,11.5245,2.8766,2.4229,106.8258,h
19016,28.9452,6.7020,2.2672,0.5351,0.2784,37.0816,13.1853,-2.9632,86.7975,247.4560,h
19017,75.4455,47.5305,3.4483,0.1417,0.0549,-9.3561,41.0562,-9.4662,30.2987,256.5166,h
19018,120.5135,76.9018,3.9939,0.0944,0.0683,5.8043,-93.5224,-63.8389,84.6874,408.3166,h
19019,187.1814,53.0014,3.2093,0.2876,0.1539,-167.3125,-168.4558,31.4755,52.7310,272.3174,h

## Waveform

- Link to data: https://hastie.su.domains/ElemStatLearn/datasets/waveform.train
- Description: Simulated waveform data
- Dimensions: 300 observations in a 21-dimensional space
- Source: page 451 of [Elements of Statistical Learning](https://hastie.su.domains/Papers/ESLII.pdf) by Hastie et al. Also featured in page 4 of [Liu et al. (2010)](https://ojs.aaai.org/index.php/AAAI/article/view/7659)

Pros:
- Well studied
- Small number of observations

Cons:
- Data were simulated, not real

In [32]:
waveform_dat=pd.read_table('https://hastie.su.domains/ElemStatLearn/datasets/waveform.train')

In [33]:
waveform_dat

,row.names,y,x.1,x.2,x.3,x.4,x.5,x.6,x.7,x.8,...,x.12,x.13,x.14,x.15,x.16,x.17,x.18,x.19,x.20,x.21
0,1,2,-1.4854,0.3470,1.6592,1.2570,1.3945,4.3182,3.9421,4.6309,...,4.2555,1.5460,1.0990,0.0588,2.0671,-0.9759,-1.0614,-0.8499,1.0453,-0.6089
1,2,1,-0.9938,1.2748,-1.1977,-0.3464,-0.3442,1.2738,0.1725,0.9997,...,2.8144,4.8261,5.9428,4.4309,5.2562,3.6981,2.7722,3.4906,0.7623,-0.5920
2,3,1,-0.2120,-0.5239,-0.6108,2.5555,-0.1607,0.2911,0.7401,-0.3071,...,4.3555,3.5097,4.2721,6.7883,3.0623,3.3953,1.5929,3.0073,2.7663,-0.7788
3,4,1,-0.4256,-0.8360,0.4756,-0.7948,-1.8930,-0.0541,-1.8688,1.1140,...,3.7252,2.3957,4.0405,5.1305,5.2005,2.9713,2.6089,1.0063,1.3321,-0.1967
4,5,2,1.0515,-0.5382,-1.3438,0.9739,0.3659,1.8218,4.8663,3.7976,...,4.6134,2.5792,2.9855,2.8388,0.1155,-1.3772,-1.5039,2.0517,0.2095,-1.7289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,2,1.3989,0.8529,0.6703,-0.8548,1.3895,0.6977,1.3740,3.5914,...,4.5715,3.6571,3.0576,1.8226,2.0845,-1.5978,1.5078,0.6975,-1.1408,-0.0718
296,297,2,-1.2946,-0.8010,-0.1358,0.8314,1.2438,0.6962,4.4738,4.0516,...,4.4018,2.4109,3.0037,3.6370,0.6103,2.5154,-0.2265,-0.1406,-0.7362,-1.1206
297,298,3,0.0289,0.7332,2.1283,2.3850,2.5421,2.9879,3.2257,0.7947,...,1.4700,0.7346,2.4204,2.1612,3.6828,3.2503,0.8433,0.6614,-0.4838,0.8712
298,299,3,0.9337,-1.9955,-0.8217,2.2748,-0.1634,1.1141,0.6481,0.5125,...,2.7666,2.8122,3.1550,5.4546,4.1912,2.2483,3.1658,1.3756,0.9956,1.1050
299,300,3,0.1432,0.7496,0.8764,0.8479,3.9517,0.6818,2.9773,0.7779,...,2.8764,3.5677,2.3591,3.4222,2.7325,1.4158,1.0129,2.7451,1.2936,-0.2678

## Vowels

- Link to data: https://www.openml.org/search?type=data&sort=runs&id=307&status=active
- Description:
- Dimensions: 990 observations in a 10-dimensional space
- Source: page 4 of [Liu et al. (2010)](https://ojs.aaai.org/index.php/AAAI/article/view/7659) but see this R [webpage](https://search.r-project.org/CRAN/refmans/customizedTraining/html/Vowel.html) for better citations and description

In [22]:
# copied from https://stackoverflow.com/questions/46401209/how-to-convert-the-arff-object-loaded-from-a-arff-file-into-a-dataframe-format
from scipy.io.arff import loadarff 
raw_data = loadarff('dat/vowels.arff')
vowels_dat = pd.DataFrame(raw_data[0])
vowels_dat

,Speaker_Number,Sex,Feature_0,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Class
0,b'Andrew',b'Male',-3.639,0.418,-0.670,1.779,-0.168,1.627,-0.388,0.529,-0.874,-0.814,b'hid'
1,b'Andrew',b'Male',-3.327,0.496,-0.694,1.365,-0.265,1.933,-0.363,0.510,-0.621,-0.488,b'hId'
2,b'Andrew',b'Male',-2.120,0.894,-1.576,0.147,-0.707,1.559,-0.579,0.676,-0.809,-0.049,b'hEd'
3,b'Andrew',b'Male',-2.287,1.809,-1.498,1.012,-1.053,1.060,-0.567,0.235,-0.091,-0.795,b'hAd'
4,b'Andrew',b'Male',-2.598,1.938,-0.846,1.062,-1.633,0.764,0.394,-0.150,0.277,-0.396,b'hYd'
...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,b'Wendy',b'Female',-3.239,3.083,-1.427,-0.202,-0.282,1.421,0.576,0.068,-0.914,0.147,b'hOd'
986,b'Wendy',b'Female',-3.753,3.605,-0.899,-0.747,-0.401,1.765,0.620,0.754,-0.835,-0.301,b'hod'
987,b'Wendy',b'Female',-3.980,2.459,0.068,0.023,0.237,1.029,-0.189,0.521,-0.773,-0.500,b'hUd'
988,b'Wendy',b'Female',-4.264,2.925,0.065,0.794,0.323,0.515,-1.282,-0.140,-0.863,-0.390,b'hud'
989,b'Wendy',b'Female',-3.291,2.324,-0.679,0.285,0.441,0.557,-0.227,0.115,-1.046,0.697,b'hed'